on:
  push:
    branches:
      - "main" 
      - "dev"

jobs:

  test:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2 
    - name: 'test'
      run: |
          go fmt $(go list ./... | grep -v /vendor/)


  publish:
    needs: test
    outputs:
      tag_commit: ${{steps.outputs_step.outputs.tag_commit}}
      tag_latest: ${{steps.outputs_step.outputs.tag_latest}}
    if: ${{ ( github.ref == 'refs/heads/main') || ( github.ref == 'refs/heads/dev') }}
    runs-on: ubuntu-latest
    steps:
      - name: Set short git sha
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-8)" >> $GITHUB_ENV
      - name: Set env variables
        run: |
            echo "TAG_COMMIT=cr.yandex/crpluk6l2pqtgar7fslr/clickhome-gorush:$(echo $GITHUB_SHA_SHORT)" >> $GITHUB_ENV
            echo "TAG_LATEST=cr.yandex/crpluk6l2pqtgar7fslr/clickhome-gorush:latest" >> $GITHUB_ENV
            
      - name: Print envs and set outputs
        id: outputs_step
        run: |
            echo $GITHUB_SHA_SHORT
            echo $TAG_COMMIT
            echo $TAG_LATEST
            echo "tag_commit=$(echo $TAG_COMMIT)" >> $GITHUB_OUTPUT
            echo "tag_latest=$(echo $TAG_LATEST)" >> $GITHUB_OUTPUT


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
      
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.REGISTRY_TOKEN }}
      

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{env.TAG_LATEST}}
            ${{env.TAG_COMMIT}}

  deploy_prod:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: publish
    uses: ./.github/workflows/deploy_prod.yml
    secrets: inherit
    with:
      tag_commit: ${{needs.publish.outputs.tag_commit}}
      tag_latest: ${{needs.publish.outputs.tag_latest}}
      
  deploy_dev:
    if: ${{github.ref == 'refs/heads/dev'}}
    needs: publish
    uses: ./.github/workflows/deploy_dev.yml
    secrets: inherit
    with:
      tag_commit: ${{needs.publish.outputs.tag_commit}}
      tag_latest: ${{needs.publish.outputs.tag_latest}}      
