name: Deploy to production

on:
  workflow_call:
      inputs:
        tag_commit: 
            required: true
            type: string
        tag_latest:
            required: true
            type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Print envs
      run: |
          echo ${{inputs.tag_commit}}
          echo ${{inputs.tag_latest}}

    - name: SSH and deploy to services
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker login --username oauth --password ${{ secrets.REGISTRY_TOKEN }} cr.yandex
            docker pull ${{ inputs.tag_commit }}
            docker container rm -f prod-gorush
            docker run -d --restart unless-stopped --network="host" --env-file=/etc/clickhom.ru/gorush/.env  -p 8088:8088 --name dev-gorush ${{inputs.tag_commit}}
